package com.harborreel.engine

enum class Symbol(val short: String, val title: String) {
    BLANK("", ""),
    ANCHOR("ANC", "Anchor"),
    COMPASS("CMP", "Compass"),
    WHEEL("WHL", "Wheel"),
    ROPE("RPE", "Rope"),
    BELL("BEL", "Bell"),
    LANTERN("LNT", "Lantern"),
    BUOY("BUOY", "Buoy"),
    SQUALL("SQL", "Squall"),
    KEEL("KEEL", "Keel"),
    PLANK("PLK", "Plank"),
    CANVAS("CNV", "Canvas"),
    GULL("GULL", "Gull"),
    LAMP("LAMP", "Lamp"),
    CLOUD("CLD", "Cloud"),
    CHEF("CHEF", "Chef"),
    NOODLE("NDL", "Noodle"),
    DUMPLING("DMP", "Dumpling"),
    TEA("TEA", "Tea"),
    FAN("FAN", "Fan"),
    STALL("STL", "Stall"),
    COIN("COIN", "Coin"),
    SCARECROW("CRW", "Scarecrow"),
    APPLE("APL", "Apple"),
    CLOVER("CLV", "Clover"),
    BOOT("BOOT", "Boot"),
    BASKET("BSK", "Basket"),
    ACE("A", "A"),
    KING("K", "K"),
    QUEEN("Q", "Q"),
    JACK("J", "J"),
    TEN("10", "10"),
    NINE("9", "9"),
}
